<?php
$levels=Array(
	"NL"	=>	Array(
		"0" => "Absolute beginners (geen ervaring)",
		"1" => "Beginners (&lt;1j)",
		"2" => "Intermediate (1-2j)",
		"3" => "Medium Advanced (2-3j)",
		"4" => "Gevorderd (3-5j)",
		"5" => "Experts (&gt;5j)",
		"P" => "Practica (voor leerlingen)"
		),
	"FR"	=>	Array(
		"0" => "Débutants absolus (pas d'expérience)",
		"1" => "Débutants (&lt; 1 an)",
		"2" => "Intermédiaire (1-2 ans)",
		"3" => "Intermédiaires avancés (2-3 ans)",
		"4" => "Avancés (3-5 ans))",
		"5" => "Experts (&gt;5 ans)",
		"P" => "Practica (pour élèves)"
		),
	"EN"	=> Array(
		"0" => "Absolute beginners (no experience)",
		"1" => "Beginners (&lt;1y)",
		"2" => "Intermediate (1-2y)",
		"3" => "Medium Advanced (2-3y)",
		"4" => "Advanced (3-5y)",
		"5" => "Experts (&gt;5y)",
		"P" => "Practica (for pupils)"
		)
);

$weekdays=Array(
	"NL"	=>	Array(
		1 => "maandag",
		2 => "dinsdag",
		3 => "woensdag",
		4 => "donderdag",
		5 => "vrijdag",
		6 => "zaterdag",
		7 => "zondag"
	),
	"FR"	=>	Array(
		1 => "lundi",
		2 => "mardi",
		3 => "mercredi",
		4 => "jeudi",
		5 => "vendredi",
		6 => "samedi",
		7 => "dimanche"
	),
	"EN"	=>	Array(
		1 => "Monday",
		2 => "Tuesday",
		3 => "Wednesday",
		4 => "Thursday",
		5 => "Friday",
		6 => "Saturday",
		7 => "Sunday"
	),
);
?>
